/**
 * Scaffolding file used to store all the setups needed to run 
 * tests automatically generated by EvoSuite
 * Thu Jul 03 07:20:22 GMT 2025
 */

package org.apache.openjpa.enhance;

import org.evosuite.runtime.annotation.EvoSuiteClassExclude;
import org.junit.BeforeClass;
import org.junit.Before;
import org.junit.After;
import org.evosuite.runtime.sandbox.Sandbox;
import org.evosuite.runtime.sandbox.Sandbox.SandboxMode;

import static org.evosuite.shaded.org.mockito.Mockito.*;
@EvoSuiteClassExclude
public class Reflection_ESTest_scaffolding {

  @org.junit.Rule
  public org.evosuite.runtime.vnet.NonFunctionalRequirementRule nfr = new org.evosuite.runtime.vnet.NonFunctionalRequirementRule();

  private org.evosuite.runtime.thread.ThreadStopper threadStopper =  new org.evosuite.runtime.thread.ThreadStopper (org.evosuite.runtime.thread.KillSwitchHandler.getInstance(), 3000);


  @BeforeClass
  public static void initEvoSuiteFramework() { 
    org.evosuite.runtime.RuntimeSettings.className = "org.apache.openjpa.enhance.Reflection"; 
    org.evosuite.runtime.GuiSupport.initialize(); 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfThreads = 100; 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfIterationsPerLoop = 10000; 
    org.evosuite.runtime.RuntimeSettings.mockSystemIn = true; 
    org.evosuite.runtime.RuntimeSettings.sandboxMode = org.evosuite.runtime.sandbox.Sandbox.SandboxMode.RECOMMENDED; 
    org.evosuite.runtime.sandbox.Sandbox.initializeSecurityManagerForSUT(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.init();
    setSystemProperties();
    initializeClasses();
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
    try { initMocksToAvoidTimeoutsInTheTests(); } catch(ClassNotFoundException e) {} 
  } 

  @Before
  public void initTestCase(){ 
    threadStopper.storeCurrentThreads();
    threadStopper.startRecordingTime();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().initHandler(); 
    org.evosuite.runtime.sandbox.Sandbox.goingToExecuteSUTCode(); 
    org.evosuite.runtime.GuiSupport.setHeadless(); 
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
    org.evosuite.runtime.agent.InstrumentingAgent.activate(); 
  } 

  @After
  public void doneWithTestCase(){ 
    threadStopper.killAndJoinClientThreads();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().safeExecuteAddedHooks(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.reset(); 
    resetClasses(); 
    org.evosuite.runtime.sandbox.Sandbox.doneWithExecutingSUTCode(); 
    org.evosuite.runtime.agent.InstrumentingAgent.deactivate(); 
    org.evosuite.runtime.GuiSupport.restoreHeadlessMode(); 
  } 

  public static void setSystemProperties() {
 
    /*No java.lang.System property to set*/
  }

  private static void initializeClasses() {
    org.evosuite.runtime.classhandling.ClassStateSupport.initializeClasses(Reflection_ESTest_scaffolding.class.getClassLoader() ,
      "org.apache.openjpa.lib.util.J2DoPrivHelper",
      "org.apache.openjpa.lib.util.J2DoPrivHelper$1",
      "org.apache.openjpa.lib.util.StreamResourceBundleProvider",
      "org.apache.openjpa.lib.util.ReferenceMap",
      "org.apache.openjpa.lib.util.J2DoPrivHelper$3",
      "org.apache.openjpa.util.OpenJPAException",
      "org.apache.openjpa.lib.util.ZipResourceBundleProvider",
      "org.apache.openjpa.lib.util.concurrent.ConcurrentReferenceHashMap$Entry",
      "org.apache.openjpa.lib.util.Localizer",
      "org.apache.openjpa.util.GeneralException",
      "org.apache.openjpa.lib.util.SizedMap",
      "org.apache.openjpa.lib.util.concurrent.ConcurrentReferenceHashMap$WeakEntry",
      "org.apache.openjpa.lib.util.J2DoPrivHelper$9",
      "org.apache.openjpa.util.UserException",
      "org.apache.openjpa.util.Exceptions",
      "org.apache.openjpa.lib.util.J2DoPrivHelper$5",
      "org.apache.openjpa.lib.util.StringUtil",
      "org.apache.openjpa.lib.util.J2DoPrivHelper$7",
      "org.apache.openjpa.lib.util.Reflectable",
      "org.apache.openjpa.lib.util.ResourceBundleProvider",
      "org.apache.openjpa.lib.util.concurrent.ConcurrentMap",
      "org.apache.openjpa.lib.util.SimpleResourceBundleProvider",
      "org.apache.openjpa.lib.util.Localizer$Message",
      "org.apache.openjpa.conf.OpenJPAVersion",
      "org.apache.openjpa.util.ExceptionInfo",
      "org.apache.openjpa.enhance.Reflection",
      "org.apache.openjpa.lib.util.concurrent.ConcurrentReferenceHashMap",
      "org.apache.openjpa.util.Exceptions$1"
    );
  } 
  private static void initMocksToAvoidTimeoutsInTheTests() throws ClassNotFoundException { 
    mock(Class.forName("org.apache.openjpa.lib.util.Reflectable", false, Reflection_ESTest_scaffolding.class.getClassLoader()));
  }

  private static void resetClasses() {
    org.evosuite.runtime.classhandling.ClassResetter.getInstance().setClassLoader(Reflection_ESTest_scaffolding.class.getClassLoader()); 

    org.evosuite.runtime.classhandling.ClassStateSupport.resetClasses(
      "org.apache.openjpa.lib.util.SimpleResourceBundleProvider",
      "org.apache.openjpa.lib.util.StreamResourceBundleProvider",
      "org.apache.openjpa.lib.util.ZipResourceBundleProvider",
      "org.apache.openjpa.lib.util.Localizer",
      "org.apache.openjpa.lib.util.J2DoPrivHelper",
      "org.apache.openjpa.lib.util.J2DoPrivHelper$5",
      "org.apache.openjpa.lib.util.concurrent.ConcurrentReferenceHashMap",
      "org.apache.openjpa.enhance.Reflection",
      "org.apache.openjpa.lib.util.StringUtil",
      "org.apache.openjpa.lib.util.J2DoPrivHelper$9",
      "org.apache.openjpa.lib.util.J2DoPrivHelper$7",
      "org.apache.openjpa.util.OpenJPAException",
      "org.apache.openjpa.util.UserException",
      "org.apache.openjpa.lib.util.Localizer$Message",
      "org.apache.openjpa.lib.util.concurrent.ConcurrentReferenceHashMap$WeakEntry",
      "org.apache.openjpa.util.GeneralException",
      "org.apache.openjpa.lib.util.J2DoPrivHelper$3",
      "org.apache.openjpa.lib.util.J2DoPrivHelper$1",
      "org.apache.openjpa.util.Exceptions$1",
      "org.apache.openjpa.util.Exceptions",
      "org.apache.openjpa.conf.OpenJPAVersion"
    );
  }
}
