/*
 * This file was automatically generated by EvoSuite
 * Thu Jul 03 07:20:22 GMT 2025
 */
/*
package org.apache.openjpa.enhance;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.shaded.org.mockito.Mockito.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.lang.annotation.Annotation;
import java.lang.reflect.Field;
import java.lang.reflect.Method;
import java.util.Set;
import org.apache.openjpa.lib.util.Reflectable;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.ViolatedAssumptionAnswer;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = false, resetStaticState = true, separateClassLoader = true)
public class Reflection_ESTest extends Reflection_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test000()  throws Throwable  {
      Reflectable reflectable0 = mock(Reflectable.class, new ViolatedAssumptionAnswer());
      doReturn(false).when(reflectable0).value();
      Reflectable reflectable1 = mock(Reflectable.class, new ViolatedAssumptionAnswer());
      doReturn(false).when(reflectable1).value();
      boolean boolean0 = Reflection.canReflect(reflectable0, reflectable1);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test001()  throws Throwable  {
      Reflectable reflectable0 = mock(Reflectable.class, new ViolatedAssumptionAnswer());
      doReturn(true).when(reflectable0).value();
      Reflectable reflectable1 = mock(Reflectable.class, new ViolatedAssumptionAnswer());
      doReturn(true).when(reflectable1).value();
      boolean boolean0 = Reflection.canReflect(reflectable0, reflectable1);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test002()  throws Throwable  {
      Class<Boolean> class0 = Boolean.class;
      Class<Annotation> class1 = Annotation.class;
      Set<Annotation> set0 = Reflection.getFieldValues((Class) class0, 3364, class1);
      assertTrue(set0.isEmpty());
  }

  @Test(timeout = 4000)
  public void test003()  throws Throwable  {
      Class<Boolean> class0 = Boolean.class;
      Boolean boolean0 = new Boolean(false);
      Method method0 = Reflection.getDeclaredMethod(class0, "compareTo", class0);
      assertNotNull(method0);
      
      Boolean boolean1 = Boolean.FALSE;
      Reflection.set((Object) boolean1, method0, (Object) boolean0);
      assertFalse(method0.isSynthetic());
      assertEquals("public int java.lang.Boolean.compareTo(java.lang.Boolean)", method0.toString());
  }

  @Test(timeout = 4000)
  public void test004()  throws Throwable  {
      Class<Boolean> class0 = Boolean.class;
      Field field0 = Reflection.findField(class0, "TYPE", true);
      Object object0 = new Object();
      Boolean boolean0 = Boolean.valueOf(false);
      // Undeclared exception!
      try { 
        Reflection.set(object0, field0, (Object) boolean0);
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // Can not set static final java.lang.Class field java.lang.Boolean.TYPE to java.lang.Boolean
         //
         verifyException("org.apache.openjpa.enhance.Reflection", e);
      }
  }

  @Test(timeout = 4000)
  public void test005()  throws Throwable  {
      Boolean boolean0 = new Boolean("dlIF,");
      short short0 = Reflection.getShort((Object) boolean0, (Method) null);
      assertEquals((short)0, short0);
  }

  @Test(timeout = 4000)
  public void test006()  throws Throwable  {
      Object object0 = new Object();
      long long0 = Reflection.getLong(object0, (Method) null);
      assertEquals(0L, long0);
  }

  @Test(timeout = 4000)
  public void test007()  throws Throwable  {
      Object object0 = new Object();
      float float0 = Reflection.getFloat(object0, (Method) null);
      assertEquals(0.0F, float0, 0.01F);
  }

  @Test(timeout = 4000)
  public void test008()  throws Throwable  {
      Object object0 = new Object();
      double double0 = Reflection.getDouble(object0, (Method) null);
      assertEquals(0.0, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test009()  throws Throwable  {
      Object object0 = new Object();
      char char0 = Reflection.getChar(object0, (Method) null);
      assertEquals('\u0000', char0);
  }

  @Test(timeout = 4000)
  public void test010()  throws Throwable  {
      Boolean boolean0 = new Boolean("dlIF,");
      byte byte0 = Reflection.getByte((Object) boolean0, (Method) null);
      assertEquals((byte)0, byte0);
  }

  @Test(timeout = 4000)
  public void test011()  throws Throwable  {
      Boolean boolean0 = Boolean.FALSE;
      boolean boolean1 = Reflection.getBoolean((Object) boolean0, (Method) null);
      assertFalse(boolean1);
  }

  @Test(timeout = 4000)
  public void test012()  throws Throwable  {
      Class<Boolean> class0 = Boolean.class;
      Class<Annotation> class1 = Annotation.class;
      Method method0 = Reflection.getDeclaredMethod(class0, "valueOf", class1);
      assertNull(method0);
  }

  @Test(timeout = 4000)
  public void test013()  throws Throwable  {
      Class<Boolean> class0 = Boolean.class;
      Class<Annotation> class1 = Annotation.class;
      // Undeclared exception!
      try { 
        Reflection.findSetter(class0, "dlIF,", class1, true);
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // Missing setter for property \"dlIF,\" in type \"class java.lang.Boolean\". 
         //
         verifyException("org.apache.openjpa.enhance.Reflection", e);
      }
  }

  @Test(timeout = 4000)
  public void test014()  throws Throwable  {
      Class<Boolean> class0 = Boolean.class;
      Boolean boolean0 = Boolean.valueOf("isc_/'x-Mk");
      Field field0 = Reflection.findField(class0, "serialVersionUID", true);
      Object object0 = Reflection.get((Object) boolean0, field0);
      // Undeclared exception!
      try { 
        Reflection.getValue(object0, "isc_/'x-Mk", true);
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // Missing field for property \"isc_/'x-Mk\" in type \"class java.lang.Long\".
         //
         verifyException("org.apache.openjpa.enhance.Reflection", e);
      }
  }

  @Test(timeout = 4000)
  public void test015()  throws Throwable  {
      Class<Boolean> class0 = Boolean.class;
      Field field0 = Reflection.findField(class0, "value", false);
      Boolean boolean0 = new Boolean("reflect-security");
      Reflection.set((Object) boolean0, field0, (Object) boolean0);
      assertTrue(field0.isAccessible());
  }

  @Test(timeout = 4000)
  public void test016()  throws Throwable  {
      Class<Boolean> class0 = Boolean.class;
      // Undeclared exception!
      try { 
        Reflection.findField(class0, (String) null, true);
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // StringEquals is not supposed to work on a null caller
         //
         verifyException("org.apache.openjpa.enhance.Reflection", e);
      }
  }

  @Test(timeout = 4000)
  public void test017()  throws Throwable  {
      Class<Boolean> class0 = Boolean.class;
      Boolean boolean0 = Boolean.FALSE;
      Field field0 = Reflection.findField(class0, "serialVersionUID", false);
      double double0 = Reflection.getDouble((Object) boolean0, field0);
      assertTrue(field0.isAccessible());
      assertEquals((-3.6658041990143688E18), double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test018()  throws Throwable  {
      Class<Boolean> class0 = Boolean.class;
      Method method0 = Reflection.getDeclaredMethod(class0, "compareTo", class0);
      Method method1 = Reflection.getDeclaringMethod(class0, method0);
      Method method2 = Reflection.mostDerived(method1, method0);
      assertNotNull(method2);
      assertNotSame(method2, method1);
      assertFalse(method2.isSynthetic());
  }

  @Test(timeout = 4000)
  public void test019()  throws Throwable  {
      Class<Boolean> class0 = Boolean.class;
      Field field0 = Reflection.findField(class0, "TYPE", false);
      Boolean boolean0 = Boolean.valueOf(false);
      Object object0 = Reflection.get((Object) boolean0, field0);
      assertNotNull(object0);
      assertEquals("TYPE", field0.getName());
      assertFalse(field0.isAccessible());
  }

  @Test(timeout = 4000)
  public void test020()  throws Throwable  {
      Class<Boolean> class0 = Boolean.class;
      Field field0 = Reflection.findField(class0, "value", false);
      boolean boolean0 = Reflection.canReflect(field0);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test021()  throws Throwable  {
      Object object0 = new Object();
      Class<Boolean> class0 = Boolean.class;
      Field field0 = Reflection.findField(class0, "value", false);
      // Undeclared exception!
      try { 
        Reflection.set(object0, field0, (short)1640);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
      }
  }

  @Test(timeout = 4000)
  public void test022()  throws Throwable  {
      Object object0 = new Object();
      Class<Boolean> class0 = Boolean.class;
      Field field0 = Reflection.findField(class0, "value", false);
      // Undeclared exception!
      try { 
        Reflection.set(object0, field0, object0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
      }
  }

  @Test(timeout = 4000)
  public void test023()  throws Throwable  {
      Object object0 = new Object();
      Class<Boolean> class0 = Boolean.class;
      Field field0 = Reflection.findField(class0, "serialVersionUID", false);
      // Undeclared exception!
      try { 
        Reflection.set(object0, field0, 0L);
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // Can not set static final long field java.lang.Boolean.serialVersionUID to (long)0
         //
         verifyException("org.apache.openjpa.enhance.Reflection", e);
      }
  }

  @Test(timeout = 4000)
  public void test024()  throws Throwable  {
      Object object0 = new Object();
      Class<Boolean> class0 = Boolean.class;
      Field field0 = Reflection.findField(class0, "value", false);
      // Undeclared exception!
      try { 
        Reflection.set(object0, field0, 172);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
      }
  }

  @Test(timeout = 4000)
  public void test025()  throws Throwable  {
      Object object0 = new Object();
      Class<Boolean> class0 = Boolean.class;
      Field field0 = Reflection.findField(class0, "serialVersionUID", false);
      // Undeclared exception!
      try { 
        Reflection.set(object0, field0, 'w');
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // Can not set static final long field java.lang.Boolean.serialVersionUID to (long)119
         //
         verifyException("org.apache.openjpa.enhance.Reflection", e);
      }
  }

  @Test(timeout = 4000)
  public void test026()  throws Throwable  {
      Object object0 = new Object();
      Class<Boolean> class0 = Boolean.class;
      Field field0 = Reflection.findField(class0, "serialVersionUID", false);
      // Undeclared exception!
      try { 
        Reflection.set(object0, field0, (byte)67);
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // Can not set static final long field java.lang.Boolean.serialVersionUID to (long)67
         //
         verifyException("org.apache.openjpa.enhance.Reflection", e);
      }
  }

  @Test(timeout = 4000)
  public void test027()  throws Throwable  {
      Class<Boolean> class0 = Boolean.class;
      Field field0 = Reflection.findField(class0, "serialVersionUID", true);
      Object object0 = new Object();
      // Undeclared exception!
      try { 
        Reflection.set(object0, 4551L, field0);
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // Can not set static final long field java.lang.Boolean.serialVersionUID to (long)4551
         //
         verifyException("org.apache.openjpa.enhance.Reflection", e);
      }
  }

  @Test(timeout = 4000)
  public void test028()  throws Throwable  {
      Object object0 = new Object();
      Class<Boolean> class0 = Boolean.class;
      Field field0 = Reflection.findField(class0, "value", true);
      // Undeclared exception!
      try { 
        Reflection.set(object0, (long) (short)1640, field0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
      }
  }

  @Test(timeout = 4000)
  public void test029()  throws Throwable  {
      Class<Boolean> class0 = Boolean.class;
      Field field0 = Reflection.findField(class0, "TYPE", false);
      Boolean boolean0 = Boolean.valueOf("TYPE");
      // Undeclared exception!
      try { 
        Reflection.set((Object) boolean0, 1.0F, field0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
      }
  }

  @Test(timeout = 4000)
  public void test030()  throws Throwable  {
      Object object0 = new Object();
      Class<Boolean> class0 = Boolean.class;
      Field field0 = Reflection.findField(class0, "value", false);
      // Undeclared exception!
      try { 
        Reflection.set(object0, (-1.0), field0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
      }
  }

  @Test(timeout = 4000)
  public void test031()  throws Throwable  {
      Class<Boolean> class0 = Boolean.class;
      Boolean boolean0 = new Boolean(false);
      Method method0 = Reflection.getDeclaredMethod(class0, "compareTo", class0);
      // Undeclared exception!
      try { 
        Reflection.getInt((Object) boolean0, method0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
      }
  }

  @Test(timeout = 4000)
  public void test032()  throws Throwable  {
      Class<Boolean> class0 = Boolean.class;
      Boolean boolean0 = new Boolean(false);
      Method method0 = Reflection.getDeclaredMethod(class0, "compareTo", class0);
      // Undeclared exception!
      try { 
        Reflection.getFloat((Object) boolean0, method0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
      }
  }

  @Test(timeout = 4000)
  public void test033()  throws Throwable  {
      Object object0 = new Object();
      Class<Boolean> class0 = Boolean.class;
      Method method0 = Reflection.getDeclaredMethod(class0, "compareTo", class0);
      // Undeclared exception!
      try { 
        Reflection.getDouble(object0, method0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
      }
  }

  @Test(timeout = 4000)
  public void test034()  throws Throwable  {
      Class<Boolean> class0 = Boolean.class;
      // Undeclared exception!
      try { 
        Reflection.getDeclaredMethod(class0, (String) null, class0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
      }
  }

  @Test(timeout = 4000)
  public void test035()  throws Throwable  {
      Class<Boolean> class0 = Boolean.class;
      Method method0 = Reflection.getDeclaredMethod(class0, "compareTo", class0);
      Object object0 = new Object();
      // Undeclared exception!
      try { 
        Reflection.getByte(object0, method0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
      }
  }

  @Test(timeout = 4000)
  public void test036()  throws Throwable  {
      Class<Boolean> class0 = Boolean.class;
      Boolean boolean0 = Boolean.FALSE;
      Field field0 = Reflection.findField(class0, "TRUE", false);
      // Undeclared exception!
      try { 
        Reflection.getBoolean((Object) boolean0, field0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
      }
  }

  @Test(timeout = 4000)
  public void test037()  throws Throwable  {
      // Undeclared exception!
      try { 
        Reflection.canReflect((Field) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.openjpa.enhance.Reflection", e);
      }
  }

  @Test(timeout = 4000)
  public void test038()  throws Throwable  {
      Class class0 = Reflection.getDeclaringClass((Method) null);
      assertNull(class0);
  }

  @Test(timeout = 4000)
  public void test039()  throws Throwable  {
      Object object0 = new Object();
      Boolean boolean0 = new Boolean(")@3&hy$*");
      Reflection.set(object0, (Method) null, (Object) boolean0);
  }

  @Test(timeout = 4000)
  public void test040()  throws Throwable  {
      Reflection.set((Object) null, (Method) null, (Object) null);
  }

  @Test(timeout = 4000)
  public void test041()  throws Throwable  {
      Object object0 = new Object();
      Reflection.set(object0, (Field) null, (short)46);
  }

  @Test(timeout = 4000)
  public void test042()  throws Throwable  {
      Reflection.set((Object) null, (Field) null, (-3458L));
  }

  @Test(timeout = 4000)
  public void test043()  throws Throwable  {
      Boolean boolean0 = Boolean.TRUE;
      Reflection.set((Object) boolean0, (Field) null, (long) (byte)0);
  }

  @Test(timeout = 4000)
  public void test044()  throws Throwable  {
      Reflection.set((Object) null, (Field) null, 1);
  }

  @Test(timeout = 4000)
  public void test045()  throws Throwable  {
      Object object0 = new Object();
      Reflection.set(object0, (Field) null, 0.0F);
  }

  @Test(timeout = 4000)
  public void test046()  throws Throwable  {
      Class<Boolean> class0 = Boolean.TYPE;
      Reflection.set((Object) class0, (Field) null, (double) 1613.2F);
      assertEquals(1041, class0.getModifiers());
  }

  @Test(timeout = 4000)
  public void test047()  throws Throwable  {
      Object object0 = new Object();
      Reflection.set(object0, (Field) null, '*');
  }

  @Test(timeout = 4000)
  public void test048()  throws Throwable  {
      Object object0 = new Object();
      Reflection.set(object0, (Field) null, (byte)31);
  }

  @Test(timeout = 4000)
  public void test049()  throws Throwable  {
      Reflection.set((Object) null, (Field) null, true);
  }

  @Test(timeout = 4000)
  public void test050()  throws Throwable  {
      Class<Boolean> class0 = Boolean.class;
      Field field0 = Reflection.findField(class0, "value", true);
      Boolean boolean0 = new Boolean(true);
      Reflection.set((Object) boolean0, field0, true);
      assertTrue(field0.isAccessible());
  }

  @Test(timeout = 4000)
  public void test051()  throws Throwable  {
      Reflection.set((Object) null, (Field) null, (Object) null);
  }

  @Test(timeout = 4000)
  public void test052()  throws Throwable  {
      Class<Boolean> class0 = Boolean.class;
      Boolean boolean0 = new Boolean(false);
      Method method0 = Reflection.getDeclaredMethod(class0, "compareTo", class0);
      // Undeclared exception!
      try { 
        Reflection.get((Object) boolean0, method0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
      }
  }

  @Test(timeout = 4000)
  public void test053()  throws Throwable  {
      Boolean boolean0 = new Boolean(true);
      Object object0 = Reflection.get((Object) boolean0, (Method) null);
      assertNull(object0);
  }

  @Test(timeout = 4000)
  public void test054()  throws Throwable  {
      Object object0 = Reflection.get((Object) null, (Method) null);
      assertNull(object0);
  }

  @Test(timeout = 4000)
  public void test055()  throws Throwable  {
      Object object0 = new Object();
      Class<Boolean> class0 = Boolean.class;
      Field field0 = Reflection.findField(class0, "value", false);
      // Undeclared exception!
      try { 
        Reflection.get(object0, field0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
      }
  }

  @Test(timeout = 4000)
  public void test056()  throws Throwable  {
      Class<Boolean> class0 = Boolean.TYPE;
      Field field0 = Reflection.findField(class0, "FALSE", false);
      assertNull(field0);
  }

  @Test(timeout = 4000)
  public void test057()  throws Throwable  {
      Class<Boolean> class0 = Boolean.class;
      // Undeclared exception!
      try { 
        Reflection.findField(class0, "getBoolean", true);
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // Missing field for property \"getBoolean\" in type \"class java.lang.Boolean\".
         //
         verifyException("org.apache.openjpa.enhance.Reflection", e);
      }
  }

  @Test(timeout = 4000)
  public void test058()  throws Throwable  {
      Class<Annotation> class0 = Annotation.class;
      Method method0 = Reflection.findGetter(class0, "3Xx", false);
      assertNull(method0);
  }

  @Test(timeout = 4000)
  public void test059()  throws Throwable  {
      // Undeclared exception!
      try { 
        Reflection.canReflect((Method) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.openjpa.enhance.Reflection", e);
      }
  }

  @Test(timeout = 4000)
  public void test060()  throws Throwable  {
      Reflectable reflectable0 = mock(Reflectable.class, new ViolatedAssumptionAnswer());
      doReturn(false, true).when(reflectable0).value();
      boolean boolean0 = Reflection.canReflect(reflectable0, reflectable0);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test061()  throws Throwable  {
      Reflectable reflectable0 = mock(Reflectable.class, new ViolatedAssumptionAnswer());
      doReturn(true, false).when(reflectable0).value();
      boolean boolean0 = Reflection.canReflect(reflectable0, reflectable0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test062()  throws Throwable  {
      Reflectable reflectable0 = mock(Reflectable.class, new ViolatedAssumptionAnswer());
      doReturn(false).when(reflectable0).value();
      boolean boolean0 = Reflection.canReflect(reflectable0, (Reflectable) null);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test063()  throws Throwable  {
      Class<Boolean> class0 = Boolean.class;
      Class<Annotation> class1 = Annotation.class;
      Set<Annotation> set0 = Reflection.getFieldValues((Class) class0, (-1968999838), class1);
      assertTrue(set0.isEmpty());
  }

  @Test(timeout = 4000)
  public void test064()  throws Throwable  {
      Class<Annotation> class0 = Annotation.class;
      Class<Boolean> class1 = Boolean.class;
      Set<Annotation> set0 = Reflection.getFieldValues((Class) class1, 25, class0);
      assertTrue(set0.isEmpty());
  }

  @Test(timeout = 4000)
  public void test065()  throws Throwable  {
      Class<Boolean> class0 = Boolean.class;
      // Undeclared exception!
      try { 
        Reflection.getFieldValues((Class) class0, 25, (Class<Annotation>) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.openjpa.enhance.Reflection", e);
      }
  }

  @Test(timeout = 4000)
  public void test066()  throws Throwable  {
      Class<Annotation> class0 = Annotation.class;
      Set<Annotation> set0 = Reflection.getFieldValues((Class) null, 12, class0);
      assertTrue(set0.isEmpty());
  }

  @Test(timeout = 4000)
  public void test067()  throws Throwable  {
      Class<Annotation> class0 = Annotation.class;
      Set<Annotation> set0 = Reflection.getFieldValues((Class) class0, (-1206), class0);
      assertTrue(set0.isEmpty());
  }

  @Test(timeout = 4000)
  public void test068()  throws Throwable  {
      Class<Annotation> class0 = Annotation.class;
      Set<String> set0 = Reflection.getPublicFieldNames(class0);
      assertTrue(set0.isEmpty());
  }

  @Test(timeout = 4000)
  public void test069()  throws Throwable  {
      Set<String> set0 = Reflection.getPublicFieldNames((Class) null);
      assertTrue(set0.isEmpty());
  }

  @Test(timeout = 4000)
  public void test070()  throws Throwable  {
      Class<Annotation> class0 = Annotation.class;
      Set<String> set0 = Reflection.getBeanStylePropertyNames(class0);
      assertEquals(0, set0.size());
  }

  @Test(timeout = 4000)
  public void test071()  throws Throwable  {
      Set<String> set0 = Reflection.getBeanStylePropertyNames((Class<?>) null);
      assertEquals(0, set0.size());
  }

  @Test(timeout = 4000)
  public void test072()  throws Throwable  {
      Class<Boolean> class0 = Boolean.TYPE;
      Set<String> set0 = Reflection.getBeanStylePropertyNames(class0);
      assertTrue(set0.isEmpty());
  }

  @Test(timeout = 4000)
  public void test073()  throws Throwable  {
      Boolean boolean0 = Boolean.valueOf(false);
      Reflection.set((Object) boolean0, (Method) null, true);
  }

  @Test(timeout = 4000)
  public void test074()  throws Throwable  {
      Reflection.set((Object) null, (Method) null, false);
  }

  @Test(timeout = 4000)
  public void test075()  throws Throwable  {
      Class<Boolean> class0 = Boolean.class;
      Field field0 = Reflection.findField(class0, "serialVersionUID", true);
      Object object0 = new Object();
      // Undeclared exception!
      try { 
        Reflection.set(object0, field0, (short) (-2430));
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // Can not set static final long field java.lang.Boolean.serialVersionUID to (long)-2430
         //
         verifyException("org.apache.openjpa.enhance.Reflection", e);
      }
  }

  @Test(timeout = 4000)
  public void test076()  throws Throwable  {
      Reflection.set((Object) null, (Field) null, (short)5);
  }

  @Test(timeout = 4000)
  public void test077()  throws Throwable  {
      Class<Boolean> class0 = Boolean.class;
      Boolean boolean0 = Boolean.valueOf(false);
      Field field0 = Reflection.findField(class0, "TRUE", false);
      // Undeclared exception!
      try { 
        Reflection.set((Object) boolean0, field0, 0L);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
      }
  }

  @Test(timeout = 4000)
  public void test078()  throws Throwable  {
      Object object0 = new Object();
      Reflection.set(object0, 0L, (Field) null);
  }

  @Test(timeout = 4000)
  public void test079()  throws Throwable  {
      Object object0 = new Object();
      Class<Boolean> class0 = Boolean.class;
      Field field0 = Reflection.findField(class0, "serialVersionUID", true);
      // Undeclared exception!
      try { 
        Reflection.set(object0, field0, (-1152499390));
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // Can not set static final long field java.lang.Boolean.serialVersionUID to (long)-1152499390
         //
         verifyException("org.apache.openjpa.enhance.Reflection", e);
      }
  }

  @Test(timeout = 4000)
  public void test080()  throws Throwable  {
      Object object0 = new Object();
      Reflection.set(object0, (Field) null, (-1719));
  }

  @Test(timeout = 4000)
  public void test081()  throws Throwable  {
      Reflection.set((Object) null, (Field) null, (-2454.335F));
  }

  @Test(timeout = 4000)
  public void test082()  throws Throwable  {
      Class<Boolean> class0 = Boolean.class;
      Field field0 = Reflection.findField(class0, "FALSE", true);
      // Undeclared exception!
      try { 
        Reflection.set((Object) class0, field0, (double) 1613.2F);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
      }
  }

  @Test(timeout = 4000)
  public void test083()  throws Throwable  {
      Reflection.set((Object) null, (Field) null, 1.0899948388632874);
  }

  @Test(timeout = 4000)
  public void test084()  throws Throwable  {
      Class<Boolean> class0 = Boolean.class;
      Field field0 = Reflection.findField(class0, "TYPE", true);
      Boolean boolean0 = Boolean.TRUE;
      // Undeclared exception!
      try { 
        Reflection.set((Object) boolean0, field0, ',');
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
      }
  }

  @Test(timeout = 4000)
  public void test085()  throws Throwable  {
      Reflection.set((Object) null, (Field) null, '6');
  }

  @Test(timeout = 4000)
  public void test086()  throws Throwable  {
      Class<Boolean> class0 = Boolean.class;
      Field field0 = Reflection.findField(class0, "TYPE", false);
      Boolean boolean0 = new Boolean("TYPE");
      // Undeclared exception!
      try { 
        Reflection.set((Object) boolean0, field0, (byte)93);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
      }
  }

  @Test(timeout = 4000)
  public void test087()  throws Throwable  {
      Reflection.set((Object) null, (Field) null, (byte) (-23));
  }

  @Test(timeout = 4000)
  public void test088()  throws Throwable  {
      Class<Boolean> class0 = Boolean.class;
      Object object0 = new Object();
      Field field0 = Reflection.findField(class0, "value", false);
      // Undeclared exception!
      try { 
        Reflection.set(object0, false, field0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
      }
  }

  @Test(timeout = 4000)
  public void test089()  throws Throwable  {
      Object object0 = new Object();
      Reflection.set(object0, (Field) null, true);
  }

  @Test(timeout = 4000)
  public void test090()  throws Throwable  {
      Class<Boolean> class0 = Boolean.class;
      Field field0 = Reflection.findField(class0, "TYPE", true);
      Boolean boolean0 = Boolean.valueOf(true);
      // Undeclared exception!
      try { 
        Reflection.set((Object) boolean0, field0, (Object) null);
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // Can not set static final java.lang.Class field java.lang.Boolean.TYPE to null value
         //
         verifyException("org.apache.openjpa.enhance.Reflection", e);
      }
  }

  @Test(timeout = 4000)
  public void test091()  throws Throwable  {
      Object object0 = new Object();
      Reflection.set(object0, (Field) null, object0);
  }

  @Test(timeout = 4000)
  public void test092()  throws Throwable  {
      Class<Boolean> class0 = Boolean.class;
      Boolean boolean0 = new Boolean(false);
      Method method0 = Reflection.getDeclaredMethod(class0, "compareTo", class0);
      // Undeclared exception!
      try { 
        Reflection.getChar((Object) boolean0, method0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
      }
  }

  @Test(timeout = 4000)
  public void test093()  throws Throwable  {
      Boolean boolean0 = Boolean.FALSE;
      int int0 = Reflection.getInt((Object) boolean0, (Method) null);
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test094()  throws Throwable  {
      Class<Boolean> class0 = Boolean.class;
      Field field0 = Reflection.findField(class0, "FALSE", false);
      Object object0 = new Object();
      // Undeclared exception!
      try { 
        Reflection.getShort(object0, field0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
      }
  }

  @Test(timeout = 4000)
  public void test095()  throws Throwable  {
      Boolean boolean0 = Boolean.TRUE;
      short short0 = Reflection.getShort((Object) boolean0, (Field) null);
      assertEquals((short)0, short0);
  }

  @Test(timeout = 4000)
  public void test096()  throws Throwable  {
      short short0 = Reflection.getShort((Object) null, (Field) null);
      assertEquals((short)0, short0);
  }

  @Test(timeout = 4000)
  public void test097()  throws Throwable  {
      Class<Boolean> class0 = Boolean.class;
      Field field0 = Reflection.findField(class0, "TYPE", false);
      Object object0 = new Object();
      // Undeclared exception!
      try { 
        Reflection.getLong(object0, field0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
      }
  }

  @Test(timeout = 4000)
  public void test098()  throws Throwable  {
      Boolean boolean0 = new Boolean("dlIF,");
      long long0 = Reflection.getLong((Object) boolean0, (Field) null);
      assertEquals(0L, long0);
  }

  @Test(timeout = 4000)
  public void test099()  throws Throwable  {
      long long0 = Reflection.getLong((Object) null, (Field) null);
      assertEquals(0L, long0);
  }

  @Test(timeout = 4000)
  public void test100()  throws Throwable  {
      Object object0 = new Object();
      Class<Boolean> class0 = Boolean.class;
      Field field0 = Reflection.findField(class0, "value", false);
      // Undeclared exception!
      try { 
        Reflection.getInt(object0, field0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
      }
  }

  @Test(timeout = 4000)
  public void test101()  throws Throwable  {
      Object object0 = new Object();
      int int0 = Reflection.getInt(object0, (Field) null);
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test102()  throws Throwable  {
      int int0 = Reflection.getInt((Object) null, (Field) null);
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test103()  throws Throwable  {
      Class<Boolean> class0 = Boolean.class;
      Field field0 = Reflection.findField(class0, "TYPE", false);
      Boolean boolean0 = new Boolean((String) null);
      // Undeclared exception!
      try { 
        Reflection.getFloat((Object) boolean0, field0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
      }
  }

  @Test(timeout = 4000)
  public void test104()  throws Throwable  {
      float float0 = Reflection.getFloat((Object) null, (Field) null);
      assertEquals(0.0F, float0, 0.01F);
  }

  @Test(timeout = 4000)
  public void test105()  throws Throwable  {
      Class<Boolean> class0 = Boolean.class;
      Field field0 = Reflection.findField(class0, "FALSE", true);
      Object object0 = new Object();
      // Undeclared exception!
      try { 
        Reflection.getDouble(object0, field0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
      }
  }

  @Test(timeout = 4000)
  public void test106()  throws Throwable  {
      Object object0 = new Object();
      double double0 = Reflection.getDouble(object0, (Field) null);
      assertEquals(0.0, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test107()  throws Throwable  {
      double double0 = Reflection.getDouble((Object) null, (Field) null);
      assertEquals(0.0, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test108()  throws Throwable  {
      Class<Boolean> class0 = Boolean.class;
      Field field0 = Reflection.findField(class0, "TYPE", false);
      Object object0 = new Object();
      // Undeclared exception!
      try { 
        Reflection.getChar(object0, field0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
      }
  }

  @Test(timeout = 4000)
  public void test109()  throws Throwable  {
      Boolean boolean0 = new Boolean("is%ljIEZ");
      char char0 = Reflection.getChar((Object) boolean0, (Field) null);
      assertEquals('\u0000', char0);
  }

  @Test(timeout = 4000)
  public void test110()  throws Throwable  {
      char char0 = Reflection.getChar((Object) null, (Field) null);
      assertEquals('\u0000', char0);
  }

  @Test(timeout = 4000)
  public void test111()  throws Throwable  {
      Class<Boolean> class0 = Boolean.class;
      Field field0 = Reflection.findField(class0, "TYPE", true);
      Boolean boolean0 = Boolean.valueOf("TYPE");
      // Undeclared exception!
      try { 
        Reflection.getByte((Object) boolean0, field0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
      }
  }

  @Test(timeout = 4000)
  public void test112()  throws Throwable  {
      Boolean boolean0 = new Boolean("dlIF,");
      byte byte0 = Reflection.getByte((Object) boolean0, (Field) null);
      assertEquals((byte)0, byte0);
  }

  @Test(timeout = 4000)
  public void test113()  throws Throwable  {
      byte byte0 = Reflection.getByte((Object) null, (Field) null);
      assertEquals((byte)0, byte0);
  }

  @Test(timeout = 4000)
  public void test114()  throws Throwable  {
      Class<Boolean> class0 = Boolean.class;
      Field field0 = Reflection.findField(class0, "value", true);
      Boolean boolean0 = Boolean.TRUE;
      boolean boolean1 = Reflection.getBoolean((Object) boolean0, field0);
      assertTrue(field0.isAccessible());
      assertTrue(boolean1);
  }

  @Test(timeout = 4000)
  public void test115()  throws Throwable  {
      Boolean boolean0 = new Boolean((String) null);
      boolean boolean1 = Reflection.getBoolean((Object) boolean0, (Field) null);
      assertFalse(boolean1);
  }

  @Test(timeout = 4000)
  public void test116()  throws Throwable  {
      boolean boolean0 = Reflection.getBoolean((Object) null, (Field) null);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test117()  throws Throwable  {
      Class<Boolean> class0 = Boolean.class;
      Field field0 = Reflection.findField(class0, "value", true);
      Object object0 = new Object();
      field0.setAccessible(true);
      // Undeclared exception!
      try { 
        Reflection.set(object0, field0, (-4937.46F));
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
      }
  }

  @Test(timeout = 4000)
  public void test118()  throws Throwable  {
      Boolean boolean0 = new Boolean("TYPE");
      Class class0 = (Class)Reflection.getValue(boolean0, "TYPE", false);
      assertFalse(class0.isSynthetic());
  }

  @Test(timeout = 4000)
  public void test119()  throws Throwable  {
      Object object0 = Reflection.getValue("get-method", "get-method", false);
      assertNull(object0);
  }

  @Test(timeout = 4000)
  public void test120()  throws Throwable  {
      Object object0 = Reflection.getValue((Object) null, "valu", false);
      assertNull(object0);
  }

  @Test(timeout = 4000)
  public void test121()  throws Throwable  {
      Boolean boolean0 = Boolean.FALSE;
      Object object0 = Reflection.get((Object) boolean0, (Field) null);
      assertNull(object0);
  }

  @Test(timeout = 4000)
  public void test122()  throws Throwable  {
      Object object0 = Reflection.get((Object) null, (Field) null);
      assertNull(object0);
  }

  @Test(timeout = 4000)
  public void test123()  throws Throwable  {
      Method method0 = Reflection.mostDerived((Method) null, (Method) null);
      assertNull(method0);
  }

  @Test(timeout = 4000)
  public void test124()  throws Throwable  {
      Class<Boolean> class0 = Boolean.class;
      Method method0 = Reflection.getDeclaredMethod(class0, "toString", class0);
      assertNull(method0);
  }

  @Test(timeout = 4000)
  public void test125()  throws Throwable  {
      Class<Boolean> class0 = Boolean.class;
      // Undeclared exception!
      try { 
        Reflection.findGetter(class0, "boolean", true);
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // Missing getter for property \"boolean\" in type \"class java.lang.Boolean\". 
         //
         verifyException("org.apache.openjpa.enhance.Reflection", e);
      }
  }

  @Test(timeout = 4000)
  public void test126()  throws Throwable  {
      Class<Boolean> class0 = Boolean.class;
      Method method0 = Reflection.findSetter(class0, "(bindngechanic=", false);
      assertNull(method0);
  }

  @Test(timeout = 4000)
  public void test127()  throws Throwable  {
      Class<Annotation> class0 = Annotation.class;
      // Undeclared exception!
      try { 
        Reflection.findSetter(class0, "booleanValue", true);
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // Missing getter for property \"booleanValue\" in type \"interface java.lang.annotation.Annotation\". 
         //
         verifyException("org.apache.openjpa.enhance.Reflection", e);
      }
  }

  @Test(timeout = 4000)
  public void test128()  throws Throwable  {
      Class<Annotation> class0 = Annotation.class;
      Method method0 = Reflection.findSetter(class0, "ACCESS_CONTROLLER", class0, false);
      assertNull(method0);
  }

  @Test(timeout = 4000)
  public void test129()  throws Throwable  {
      Reflection.set((Object) null, true, (Field) null);
  }

  @Test(timeout = 4000)
  public void test130()  throws Throwable  {
      Object object0 = new Object();
      Reflection.set(object0, 0.0F, (Field) null);
  }

  @Test(timeout = 4000)
  public void test131()  throws Throwable  {
      Boolean boolean0 = new Boolean("dlIF,");
      Reflection.set((Object) boolean0, (double) 0L, (Field) null);
  }

  @Test(timeout = 4000)
  public void test132()  throws Throwable  {
      Boolean boolean0 = new Boolean("dlIF,");
      Reflection.set((Object) boolean0, (byte) (-95), (Field) null);
  }

  @Test(timeout = 4000)
  public void test133()  throws Throwable  {
      Reflection.set((Object) null, (Method) null, (byte)3);
  }

  @Test(timeout = 4000)
  public void test134()  throws Throwable  {
      Reflection.set((Object) null, (Method) null, 1813.0);
  }

  @Test(timeout = 4000)
  public void test135()  throws Throwable  {
      Reflection.set((Object) null, (Method) null, 'v');
  }

  @Test(timeout = 4000)
  public void test136()  throws Throwable  {
      Object object0 = new Object();
      Reflection.set(object0, (Method) null, (float) 0L);
  }

  @Test(timeout = 4000)
  public void test137()  throws Throwable  {
      Object object0 = new Object();
      Reflection.set(object0, (Method) null, 0L);
  }

  @Test(timeout = 4000)
  public void test138()  throws Throwable  {
      Reflection reflection0 = new Reflection();
  }

  @Test(timeout = 4000)
  public void test139()  throws Throwable  {
      Reflection.set((Object) null, (Method) null, (-295));
  }

  @Test(timeout = 4000)
  public void test140()  throws Throwable  {
      Boolean boolean0 = new Boolean("dlIF,");
      Reflection.set((Object) boolean0, (short) (-20037), (Field) null);
  }

  @Test(timeout = 4000)
  public void test141()  throws Throwable  {
      Boolean boolean0 = new Boolean("dlIF,");
      Reflection.set((Object) boolean0, '-', (Field) null);
  }

  @Test(timeout = 4000)
  public void test142()  throws Throwable  {
      Reflection.set((Object) null, 904, (Field) null);
  }

  @Test(timeout = 4000)
  public void test143()  throws Throwable  {
      Reflection.set((Object) null, (Method) null, (short)4);
  }

  @Test(timeout = 4000)
  public void test144()  throws Throwable  {
      Class<Boolean> class0 = Boolean.class;
      Method method0 = Reflection.getDeclaringMethod(class0, (Method) null);
      assertNull(method0);
  }

  @Test(timeout = 4000)
  public void test145()  throws Throwable  {
      Class<Boolean> class0 = Boolean.class;
      Set<String> set0 = Reflection.getPublicFieldNames(class0);
      float float0 = Reflection.getFloat((Object) set0, (Field) null);
      assertEquals(3, set0.size());
      assertEquals(0.0F, float0, 0.01F);
  }

  @Test(timeout = 4000)
  public void test146()  throws Throwable  {
      Boolean boolean0 = Boolean.TRUE;
      Reflection.set((Object) null, (Object) boolean0, (Field) null);
  }
}
*/
